name: MIPSFusion
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2023.05.30=h06a4308_0
  - certifi=2022.12.7=py37h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=1.1.1u=h7f8727e_0
  - pip=22.3.1=py37h06a4308_0
  - python=3.7.16=h7a1cb2a_0
  - readline=8.2=h5eee18b_0
  - setuptools=65.6.3=py37h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.38.4=py37h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
    - argcomplete==3.0.8
    - backcall==0.2.0
    - charset-normalizer==3.2.0
    - cycler==0.11.0
    - debugpy==1.6.7
    - decorator==5.1.1
    - entrypoints==0.4
    - fonttools==4.38.0
    - fvcore==0.1.5.post20221221
    - idna==3.4
    - imageio==2.30.0
    - importlib-metadata==6.7.0
    - iopath==0.1.10
    - ipykernel==6.16.2
    - ipython==7.34.0
    - ipywidgets==8.0.6
    - jedi==0.18.2
    - jupyter-client==7.4.9
    - jupyter-core==4.12.0
    - jupyterlab-widgets==3.0.8
    - kiwisolver==1.4.4
    - matplotlib==3.5.3
    - matplotlib-inline==0.1.6
    - natsort==8.3.1
    - nest-asyncio==1.5.7
    - numpymarchingcubes==0.0.1
    - packaging==23.1
    - pandas==1.3.5
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.5.0
    - portalocker==2.7.0
    - prompt-toolkit==3.0.39
    - psutil==5.9.5
    - ptyprocess==0.7.0
    - pygments==2.15.1
    - pyparsing==3.0.9
    - pypose==0.3.6
    - python-dateutil==2.8.2
    - pytz==2023.3
    - pyyaml==6.0
    - pyzmq==25.1.0
    - requests==2.31.0
    - scipy==1.7.3
    - six==1.16.0
    - tabulate==0.9.0
    - termcolor==2.3.0
    - tinycudann==1.7
    - torch==1.13.1+cu116
    - torchaudio==0.13.1+cu116
    - torchvision==0.14.1+cu116
    - tornado==6.2
    - traitlets==5.9.0
    - trimesh==3.22.1
    - typing-extensions==4.7.1
    - urllib3==2.0.4
    - wcwidth==0.2.6
    - widgetsnbextension==4.0.8
    - yacs==0.1.8
prefix: /home/javens/anaconda3/envs/MIPSFusion
