inherit_from: configs/FastCaMo-synth/FastCaMo-synth.yaml

mapping:
  bound: [[-0.6, 2.95], [0.5, 7.05], [-1.15, 3.05]]
  marching_cubes_bound: [[-0.6, 2.95], [0.5, 7.05], [-1.15, 3.05]]

data:
  datadir: /media/javens/TYJ_lab1T/Dataset/FastCaMo-Synth/raw/apartment_2
  trainskip: 1
  output: output/FastCaMo-synth/apartment_2
  exp_name: "0"
  starting_frame: -1