inherit_from: configs/FastCaMo-large/FastCaMo-large.yaml

mapping:
  bound: [[-3.1, 1.7], [-4.2, 8.0], [-1.2, 12.0]]
  marching_cubes_bound: [[-3.1, 1.7], [-4.2, 8.0], [-1.2, 12.0]]

data:
  datadir: /media/javens/TYJ_lab1T/Dataset/NS_VF/IndoorLarge/stairs2
  trainskip: 1
  output: output/FastCaMo-large/stairs2
  exp_name: "0"
  starting_frame: -1